package com.hiapk.regulate;

public class SmsSet {
	public static String YD = "中国移动";
	public static String LT = "中国联通";
	public static String DX = "中国电信";
	public static String LT2G = "联通2G";
	public static String LT3G = "联通沃3G";

	public static void smsSet(String province,String operator,String brand){
		//一样的先设置
		if(operator.equalsIgnoreCase(YD)){			
			Regulate.smsNum.setText("10086");
		}
		if(operator.equalsIgnoreCase(LT)){			
			Regulate.smsNum.setText("10010");
		}
		if(operator.equalsIgnoreCase(DX)){
			Regulate.smsText.setText("108");
			Regulate.smsNum.setText("10001");
		}
		//不同省份
		if(province.equalsIgnoreCase("北京")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("CXGLL");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					Regulate.smsText.setText("CXGPRS");				
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("1071");			
				}
			}			
		}
		if(province.equalsIgnoreCase("广东")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("CXLL");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					Regulate.smsText.setText("CXGPRSLL");				
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("CXLL");			
				}
			}			
		}
		if(province.equalsIgnoreCase("上海")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("CXLL");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					Regulate.smsText.setText("CXLL");				
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("1071");			
				}
			}			
		}
		if(province.equalsIgnoreCase("天津")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("CXLL");
			}
			if(operator.equalsIgnoreCase(LT)){				
				Regulate.smsText.setText("YHCX");
			}			
		}
		if(province.equalsIgnoreCase("重庆")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("10056");
			}
			if(operator.equalsIgnoreCase(LT)){				
				Regulate.smsText.setText("797");
			}			
		}
		if(province.equalsIgnoreCase("辽宁")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("CXLL");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					Regulate.smsText.setText("LLCXGSM");				
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("CXLL");			
				}
			}			
		}
		if(province.equalsIgnoreCase("江苏")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("CXGPRS");
			}
			if(operator.equalsIgnoreCase(LT)){
				Regulate.smsText.setText("705");
			}			
		}
		if(province.equalsIgnoreCase("湖北")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("CXSJLL");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					Regulate.smsText.setText("SJLL");				
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("CXLL");			
				}
			}			
		}
		if(province.equalsIgnoreCase("四川")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("HF");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					Regulate.smsText.setText("1071");				
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("CXLL");			
				}
			}			
		}
		if(province.equalsIgnoreCase("陕西")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("3053");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					//该地区不支持
					 defSms();			
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("1071");			
				}
			}			
		}
		if(province.equalsIgnoreCase("河北")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("5011");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					Regulate.smsText.setText("7011#201203");				
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("CXLL");			
				}
			}			
		}
		if(province.equalsIgnoreCase("山西")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("107");
			}
			if(operator.equalsIgnoreCase(LT)){				
				Regulate.smsText.setText("1071");
			}			
		}
		if(province.equalsIgnoreCase("河南")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("603");
			}
			if(operator.equalsIgnoreCase(LT)){
				Regulate.smsText.setText("CXLL");	
			}
			if(operator.equalsIgnoreCase(DX)){
				Regulate.smsText.setText("506");	
			}
		}
		if(province.equalsIgnoreCase("吉林")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("1173");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					Regulate.smsText.setText("7011");				
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("1071");			
				}
			}			
		}
		if(province.equalsIgnoreCase("黑龙江")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("CXLL");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					//不支持
					defSms();
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("1071");			
				}
			}			
		}
		if(province.equalsIgnoreCase("内蒙古")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("CXGPRS");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					Regulate.smsText.setText("519");				
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("1071");			
				}
			}			
		}
		if(province.equalsIgnoreCase("山东")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("3");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					Regulate.smsText.setText("412");				
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("1071");			
				}
			}			
		}
		if(province.equalsIgnoreCase("安徽")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("703");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					Regulate.smsText.setText("LL");				
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsNum.setText("10655898");
					Regulate.smsText.setText("LL");			
				}
			}			
		}
		if(province.equalsIgnoreCase("浙江")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("1561");
			}
			if(operator.equalsIgnoreCase(LT)){
				Regulate.smsText.setText("1071");
			}			
		}
		if(province.equalsIgnoreCase("福建")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("18");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					//不支持
					defSms();
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("CXLL");			
				}
			}			
		}
		if(province.equalsIgnoreCase("湖南")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("11803");
			}
			if(operator.equalsIgnoreCase(LT)){				
				Regulate.smsText.setText("CXLL");	
			}			
		}
		if(province.equalsIgnoreCase("广西")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("CXLL");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					Regulate.smsText.setText("SSLL");				
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("CXLL");			
				}
			}			
		}
		if(province.equalsIgnoreCase("江西")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("CXGPRS");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					//不支持
					defSms();
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("1071");			
				}
			}
			if(operator.equalsIgnoreCase(DX)){
				Regulate.smsText.setText("3535");
			}
		}
		if(province.equalsIgnoreCase("贵州")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("7013");
			}
			if(operator.equalsIgnoreCase(LT)){
				Regulate.smsText.setText("CXLL");	
			}			
		}
		if(province.equalsIgnoreCase("云南")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("CXLL");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					//不支持
					defSms();
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("CXLL");			
				}
			}			
		}
		if(province.equalsIgnoreCase("西藏")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("CXTCSY");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					//不支持
					defSms();
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("CXLL");			
				}
			}			
		}
		if(province.equalsIgnoreCase("海南")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("106");
			}
			if(operator.equalsIgnoreCase(LT)){
				Regulate.smsText.setText("CXLL");	
			}			
		}
		if(province.equalsIgnoreCase("甘肃")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("TCCX");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					//不支持
					defSms();
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("1071");			
				}
			}
			if(operator.equalsIgnoreCase(DX)){
				Regulate.smsText.setText("151");
			}
		}
		if(province.equalsIgnoreCase("宁夏")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("17*05#");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					//不支持		
					defSms();
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("1071");			
				}
			}		
			if(operator.equalsIgnoreCase(DX)){
				Regulate.smsText.setText("CXLL");
			}
		}
		if(province.equalsIgnoreCase("青海")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("30617");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					//不支持
					defSms();
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("CXLL");			
				}
			}			
		}
		if(province.equalsIgnoreCase("新疆")){
			if(operator.equalsIgnoreCase(YD)){
				Regulate.smsText.setText("108");
			}
			if(operator.equalsIgnoreCase(LT)){
				if(brand.equalsIgnoreCase(LT2G)){
					//不支持		
					defSms();
				}
				if(brand.equalsIgnoreCase(LT3G)){
					Regulate.smsText.setText("2082");			
				}
			}			
		}
		

	}

	public static void defSms(){
		
		Regulate.smsText.setText("CXLL");
	}

}
